#include "commands/command_white.h"
#include "commands/command_black.h"
#include "commands/command_time.h"
#include "commands/command_otim.h"
#include "commands/command_rating.h"
#include "commands/command_new.h"
#include "commands/command_result.h"
#include "commands/command_memory.h"
