#include "commands/command_debugFrontend.h"
#include "commands/command_xboard.h"
#include "commands/command_protover.h"
#include "commands/command_random.h"
#include "commands/command_computer.h"
#include "commands/command_sd.h"
